# kubernetes/base/ollama-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        # --- CORRECTED STARTUP SCRIPT ---
        # This version runs the server in the background, pulls the model,
        # and then waits for the server process. This is the correct sequence.
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Ollama container starting..."
            ollama serve &
            pid=$!
            echo "Ollama server started in background with PID: $pid"
            sleep 5
            echo "Attempting to pull model 'llama3:8b'..."
            ollama pull llama3:8b
            echo "Model pull complete."
            echo "Ollama is running. Waiting for server process to exit..."
            wait $pid
        # --- END OF CORRECTION ---
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-models-storage
          mountPath: /root/.ollama
        # The startupProbe is still essential. It tells Kubernetes to wait
        # until the server is responsive after the model pull is complete.
        startupProbe:
          httpGet:
            path: / # The root API endpoint should return OK
            port: 11434
          # Probe configuration gives the pod up to 5 minutes 
          # (30 failures * 10s) to become fully ready.
          failureThreshold: 30
          periodSeconds: 10
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: "4"
            memory: "16Gi"
          requests:
            nvidia.com/gpu: 1
            cpu: "1"
            memory: "8Gi"
      volumes:
      - name: ollama-models-storage
        persistentVolumeClaim:
          claimName: ollama-models-pvc