apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-simulator
  labels:
    app: edge-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-simulator
  template:
    metadata:
      labels:
        app: edge-simulator
    spec:
      containers:
      - name: edge-simulator-app
        image: sdsajoshi/edge-simulator-app:latest # IMPORTANT: Replace with your image
        env:
        # Environment variable for the MQTT Broker service endpoint
        - name: MQTT_BROKER_HOSTNAME
          value: "mqtt-broker-service"
        # Environment variable for the PCAI App service endpoint
        - name: PCAI_AGENT_TRIGGER_ENDPOINT
          value: "http://pcai-app-service:5000/api/v1/analyze_trigger"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"