# kubernetes/base/edge-simulator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-simulator
  labels:
    app: edge-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-simulator
  template:
    metadata:
      labels:
        app: edge-simulator
    spec:
      containers:
      - name: edge-simulator-app
        image: sdsajoshi/edge-simulator-app:latest # IMPORTANT: Replace with your actual image
        # --- MODIFICATION: Added CPU and Memory resources ---
        resources:
          requests:
            cpu: "100m" # 0.1 of a CPU core
            memory: "128Mi"
          limits:
            cpu: "500m" # 0.5 of a CPU core
            memory: "256Mi"
        env:
        - name: PCAI_AGENT_TRIGGER_ENDPOINT
          value: "http://pcai-app-service:5000/api/v1/analyze_trigger"