# kubernetes/base/ollama-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        # These labels must match the selector in ollama-service.yaml
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        # --- MODIFICATION: Override container command to pull model then serve ---
        # This ensures the model is available before the server starts accepting connections.
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Ollama container starting..."
            echo "Attempting to pull model 'llama3:8b'. This may take a few minutes on first run..."
            ollama pull llama3:8b
            echo "Model pull complete."
            echo "Starting Ollama server..."
            ollama serve
        # --- END MODIFICATION ---
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-models-storage
          mountPath: /root/.ollama
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
            cpu: "1"
            memory: "8Gi"
      volumes:
      - name: ollama-models-storage
        persistentVolumeClaim:
          claimName: ollama-models-pvc