# kubernetes/base/ollama-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama-pull-model-init
        image: ollama/ollama:latest
        command: ["ollama", "pull", "llama3:8b"]
        volumeMounts:
        - name: ollama-models-storage
          mountPath: /root/.ollama
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-models-storage
          mountPath: /root/.ollama
        # --- MODIFICATION: Added CPU and Memory resources ---
        resources:
          requests:
            # Requesting significant CPU and RAM as LLM serving can be demanding
            # even outside the GPU.
            cpu: "1"
            memory: "8Gi"
            nvidia.com/gpu: 1 # GPU Request
          limits:
            # Setting generous limits to avoid being killed under load
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1 # GPU Limit
      volumes:
      - name: ollama-models-storage
        persistentVolumeClaim:
          claimName: ollama-models-pvc