# kubernetes/base/pcai-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcai-app
  labels:
    app: pcai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcai-app
  template:
    metadata:
      labels:
        app: pcai-app
    spec:
      containers:
      - name: pcai-app
        image: sdsajoshi/pcai-app:latest # IMPORTANT: Replace with your actual image
        ports:
        - containerPort: 5000
        # --- MODIFICATION: Added CPU and Memory resources ---
        resources:
          requests:
            cpu: "250m" # 0.25 of a CPU core
            memory: "512Mi" # 512 Mebibytes
          limits:
            cpu: "1" # 1 full CPU core
            memory: "1Gi" # 1 Gibibyte
        envFrom:
        - secretRef:
            name: pcai-app-credentials
        - secretRef:
            name: opsramp-credentials
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: kb-volume
          mountPath: /app/knowledge_base_files
      volumes:
      - name: config-volume
        configMap:
          name: pcai-app-config
          items:
            - key: demo_config.yaml
              path: demo_config.yaml
      - name: kb-volume
        configMap:
          name: pcai-app-config