# config/demo_config.yaml

# ----------------------------------------------------------------------
# Configuration for the AI-Driven Predictive Maintenance Demo
# ----------------------------------------------------------------------

# --- Global Settings ---
company_name_short: "DemoCorp"

# --- MQTT Broker Settings ---
mqtt:
  # For local runs, the broker will be on localhost.
  # For Kubernetes, this is overridden by the MQTT_BROKER_HOSTNAME env var
  # which points to the K8s service name 'mqtt-broker-service'.
  broker_hostname: "localhost"
  broker_port: 1883
  # The topic where sensor data will be published.
  sensor_topic: "hpe/demo/turbine/007/sensors"

# --- IoT Sensor Simulator Settings ---
iot_sensor_simulator:
  asset_id_prefix: "{company_name_short}_Turbine"
  default_asset_number: 7
  data_interval_seconds: 2
  base_temp_c: 42.0 # Should match the internal base_temp_c in TurbineSensor

# --- Aruba Edge Simulator Settings ---
aruba_edge_simulator:
  device_id_template: "Edge_Sim_{company_name_short}_Node{id:03d}"
  default_device_id_num: 1
  # For local runs, this points to localhost.
  # For Kubernetes, this is overridden by the PCAI_AGENT_TRIGGER_ENDPOINT env var
  # which points to the K8s service name 'pcai-app-service'.
  pcai_agent_trigger_endpoint: "http://localhost:5000/api/v1/analyze_trigger"
  thresholds:
    temperature_critical_c: 55.0
    vibration_anomaly_amp_g: 1.5 
    acoustic_critical_band_db: 70.0

# --- PCAI Agent Application Settings ---
pcai_app:
  agent_id_prefix_template: "PCAI_Agent_{company_name_short}" 
  listen_host: "0.0.0.0"
  listen_port: 5000
  knowledge_base_path: "/app/knowledge_base_files" # Path inside K8s container
  
  llm_config:
    provider: "ollama" 
    ollama:
      model_name: "llama3:8b" 
      # For local runs, Ollama is at localhost. For K8s, it's the service name.
      api_base_url: "http://localhost:11434" 
      request_timeout_seconds: 180

  opsramp:
    env_var_tenant_id: "OPSRAMP_TENANT_ID"
    env_var_api_key: "OPSRAMP_API_KEY"
    env_var_api_secret: "OPSRAMP_API_SECRET"
    api_hostname: "hpekaops.api.pov.opsramp.com"
    token_endpoint_path: "/tenancy/auth/oauth/token"
    alert_endpoint_path: "/api/v2/tenants/{tenantId}/alerts"
    # IMPORTANT: Replace with the unique ID of the resource you created in OpsRamp
    turbine_resource_id: "957836fe-7986-46da-bc28-b5d5cca08c85"

  servicenow:
    # IMPORTANT: Replace with YOUR actual ServiceNow developer instance HOSTNAME
    instance_hostname: "dev194183.service-now.com"
    env_var_api_user: "SERVICENOW_API_USER"
    env_var_api_password: "SERVICENOW_API_PASSWORD"
    target_table: "incident"
    default_assignment_group: "Mechanical Maintenance Team"
    custom_fields:
      source_system: "u_source_system"
      ai_diagnosis_confidence: "u_ai_diagnosis_confidence"
      ai_reasoning: "u_ai_reasoning"
      recommended_actions: "u_ai_recommended_actions"
      required_parts: "u_ai_required_parts"

  diagnosis:
    confidence_threshold_for_action: 0.70