# config/demo_config.yaml

# ----------------------------------------------------------------------
# Configuration for the AI-Driven Predictive Maintenance Demo
# ----------------------------------------------------------------------

# --- Global Settings ---
company_name_short: "DemoCorp"

# --- Internal MQTT Broker Settings ---
# FIX: Renamed 'broker_hostname' to 'host' to match the code.
# The 'mqtt' key remains the same.
mqtt:
  host: "localhost"
  port: 1883
  sensor_topic: "hpe/demo/turbine/007/sensors"

# --- ThingsBoard IoT Platform MQTT Configuration ---
thingsboard:
  host: "localhost"
  port: 1884
  # FIX: You MUST replace this placeholder with the real token from your
  # ThingsBoard device's "Access token" field.
  device_token: "VeoL2kBuBjrtv8Bqb9hK"

# --- IoT Sensor Simulator Settings ---
iot_sensor_simulator:
  asset_id_prefix: "{company_name_short}_Turbine"
  default_asset_number: 7
  data_interval_seconds: 5 # Increased for easier log reading during debug
  base_temp_c: 42.0
  vibration_normal_range: [0.1, 0.5]
  acoustic_normal_range: [20.0, 35.0]
  anomaly_start_chance: 0.15
  anomaly_stop_chance: 0.4
  anomaly_vibration_factor: 10.0

# --- Aruba Edge Simulator Settings ---
aruba_edge_simulator:
  device_id_template: "Edge_Sim_{company_name_short}_Node{id:03d}"
  default_device_id_num: 1
  pcai_agent_trigger_endpoint: "http://localhost:5000/api/v1/analyze_trigger"
  thresholds:
    temperature_critical_c: 55.0
    vibration_anomaly_amp_g: 1.5 
    acoustic_critical_band_db: 70.0

# --- PCAI Agent Application Settings ---
pcai_app:
  agent_id_prefix_template: "PCAI_Agent_{company_name_short}" 
  listen_host: "0.0.0.0"
  listen_port: 5000
  knowledge_base_path: "knowledge_base_files" # Use relative path for local run
  
  llm_config:
    provider: "ollama" 
    ollama:
      model_name: "llama3:8b" 
      api_base_url: "http://localhost:11434" 
      request_timeout_seconds: 180

  opsramp:
    env_var_tenant_id: "OPSRAMP_TENANT_ID"
    env_var_api_key: "OPSRAMP_API_KEY"
    env_var_api_secret: "OPSRAMP_API_SECRET"
    api_hostname: "hpekaops.api.pov.opsramp.com"
    token_endpoint_path: "/tenancy/auth/oauth/token"
    alert_endpoint_path: "/api/v2/tenants/{tenantId}/alerts"
    turbine_resource_id: "957836fe-7986-46da-bc28-b5d5cca08c85"

  servicenow:
    instance_hostname: "dev194183.service-now.com"
    env_var_api_user: "SERVICENOW_API_USER"
    env_var_api_password: "SERVICENOW_API_PASSWORD"
    target_table: "incident"
    default_assignment_group: "Mechanical Maintenance Team"
    custom_fields:
      source_system: "u_source_system"
      ai_diagnosis_confidence: "u_ai_diagnosis_confidence"
      ai_reasoning: "u_ai_reasoning"
      recommended_actions: "u_ai_recommended_actions"
      required_parts: "u_ai_required_parts"

  diagnosis:
    confidence_threshold_for_action: 0.70